server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          
        - id: sistema-ponto
          uri: http://localhost:8082
          predicates:
            - Path=/api/**
          filters:
            - name: JwtAuthFilter
            - StripPrefix=1

# Configuração do Auth Service
auth:
  service:
    url: http://localhost:8081

# JWT - deve ser igual ao auth-service
jwt:
  secret: minhachavesecretasuperseguraparaojwt123456789
  expiration: 3600000  # 1 hora em vez de 24h

logging:
  level:
    com.exemplo.gateway: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/api-gateway.log